apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  targetCPUUtilizationPercentage: 60
